# Generated by Django 2.1.1 on 2020-08-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bjnewsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='1', max_length=500, null=True),
        ),
    ]
